name: Trusty Packbeast
allow_many: true
mana: 2W
types:
  - creature
subtypes:
  - beast
power: 2
toughness: 3
triggers:
  - on: enter
    by: self
    do: return
    target:
      type: artifact
      controller: self
      from: graveyard
      to: hand

