# ------------------------
# DONT CHANGE THIS SECTION
version: 0.1
# ------------------------

# USER CONFIG HERE. TODO: make it count XD LUL.
# -------------------------------------------
default_server_ip: 127.0.0.1
default_server_port: 62442
# initial player's HP
initial_HP: 20
# maximum hand size
max_hand: 7
# minimal library size
min_library: 60
# maximum number of rules in sideboard
max_sideboard: 15
# acceptable: new(london), old(vancouver)
mulligan: new
